name: k6 Load Test

on:
  push:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Grafana k6
        uses: grafana/setup-k6-action@main
      - name: Run local k6 test
        uses: grafana/run-k6-action@main
      - uses: ./
        with:
          path: K6-Test.js
